[package]
name = "palettify"
version = "0.1.0"
authors = ["jo <nic.berbiche@gmail.com>"]
publish = false
edition = "2021"

[dependencies]
image = "0.25.5"
regex = "1.11.1"
ndarray = "0.14"
ndarray-linalg = { version = "0.16", features = ["openblas-static"] }
